name: Handle Release Rules
on:
  push:
    branches:
      - main

jobs:
  run_ci:
    name: 'Run CI Pipeline'
    uses: ./.github/workflows/CI.yml

  commit_release:
    runs-on: ubuntu-latest
    environment: production
    needs: [run_ci]
    name: 'Commit Release Bots Actions'
    steps:
      - uses: actions/checkout@v3
      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'feat,Feat,new,New,Minor,minor'
          major-wording: 'Rel,rel,Major,major'
          skip-tag: 'true'
          skip-commit: 'true'
          skip-push: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🤖: New build [skip ci]'
          commit_user_name: 'kevin[bot]'
