name: Handle Release Rules
on:
  push:
    branches:
      - main

jobs:
  run_lint:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment: production
    name: 'Run Code Linters'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run lint

  run_tests:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    needs: run_lint
    runs-on: ubuntu-latest
    environment: production
    name: 'Run Code Tests'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run test

  run_build:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    needs: [run_lint, run_tests]
    runs-on: ubuntu-latest
    environment: production
    name: 'Run Code Build'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run build

  bump_version:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment: production
    needs: [run_lint, run_tests, run_build]
    name: 'Bump Package Version'
    steps:
      - uses: actions/checkout@v3
      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'feat,Feat,new,New,Minor,minor'
          major-wording: 'Rel,rel,Major,major'
          skip-tag: 'true'
          commit-message: '🤖: Package version to {{version}}'

  commit_release:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment: production
    needs: [run_lint, run_tests, run_build, bump_version]
    name: 'Commit Release Bots Actions'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🤖: New build'
          commit_user_name: 'kevin[bot]'


